---
# python proxy setup 

- name: copy personalized README.md (template/jinja j2)
  tags: python-proxy-setup
  template: 
    src: README.md.j2 
    dest: "/home/{{ item }}/README.md" 
    owner: "{{ item }}"
    group: "{{ item }}" 
    mode: 0755
  with_items: "{{ users }}"

- name: create output directory
  tags: python-proxy-setup
  file: 
    path: "/opt/data/output/{{ item }}"
    state: directory
    owner: "{{ item }}"
    group: root
    mode: 0775
    recurse: yes
  with_items: "{{ users }}"

- name: Create output symbolic link 
  file:
    src: "/opt/data/output/{{ item }}"
    dest: "/home/{{ item }}/output"
    owner: "{{ item }}"
    group: root
    state: link
  with_items: "{{ users }}"

- name: Create input symbolic link 
  file:
    src: "/opt/data/input/"
    dest: "/home/{{ item }}/input"
    owner: "{{ item }}"
    group: root
    state: link
  with_items: "{{ users }}"